### PR TITLE
feat: add cargo-vckpg for vcpkg vendor and deps vendor

### PR DESCRIPTION
**Pull request by CGQAQ**
image

### CODE REVIEW

**Comment by bennyboer** [comment]
Cool!

**Comment by bennyboer** [comment]
During `cargo publish` it says:

```
error: failed to verify package tarball

Caused by:
  Source directory was modified by build.rs during cargo publish. Build scripts should not modify anything outside of OUT_DIR.
  Added: C:\repo\harfbuzz-bindings\target\package\harfbuzz-bindings-0.2.0\Cargo.lock
```

Any idea why the change would cause this?

**Comment by CGQAQ** [comment]
image


@bennyboer It's this line somehow cause the error, but this piece of code does not touch the src dir, weird


ref: mcgoo/cargo-vcpkg#18

**Comment by bennyboer** [comment]
I got it published either way using the `no-verify` flag 😄

**Pull request merged**
